spring:
  application:
    name: saas-pedidos

  datasource:
    url: jdbc:postgresql://localhost:5433/saas_pedidos
    username: admin
    password: password123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate # Use 'update' para desenvolvimento, 'validate' para produção
    show-sql: true
    properties:
      multiTenancy: DISCRIMINATOR
      tenant_identifier_resolver: com.pedinun.pedinunfood.tenant.TenantResolver
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

# Placeholder para o Spring Security / JWT
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24h